name: Build & Deploy to Render

on:
  push:
    branches:
      - master

jobs:
  build:
    name:  Compilation Java
    runs-on: ubuntu-latest

    steps:
    - name:  Cloner le dépôt
      uses: actions/checkout@v3

    - name:  Installer Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Télécharger Gson
      run: |
        mkdir -p lib
        curl -L -o lib/gson-2.8.9.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.9/gson-2.8.9.jar

    - name:  Compiler le projet
      run: javac -cp "lib/gson-2.8.9.jar" src/*.java

  deploy:
    name:  Déploiement Render
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name:  Appeler le webhook Render
      run: echo "✅ Déploiement automatique effectué via Render car GitHub auto-deploy est activé"